# $kbyanc: dyntrace/data/Makefile,v 1.1 2004/12/23 00:22:35 kbyanc Exp $

PREFIX?=	/usr/local
FILESDIR=	${PREFIX}/share/dyntrace

FILES=		oplist-x86.xml

beforeinstall:
	mkdir -p ${FILESDIR}

.include <bsd.prog.mk>
